// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBm2kRSx_CsFA1BhvcU8Is6sU5YxUcLwbI',
    appId: '1:392841827787:web:your_web_app_id_here',
    messagingSenderId: '392841827787',
    projectId: 'health-care-app-791f6',
    authDomain: 'health-care-app-791f6.firebaseapp.com',
    storageBucket: 'health-care-app-791f6.firebasestorage.app',
    measurementId: 'G-YOUR_MEASUREMENT_ID',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBm2kRSx_CsFA1BhvcU8Is6sU5YxUcLwbI',
    appId: '1:392841827787:android:8e6c6c81f6c2540ca4924e',
    messagingSenderId: '392841827787',
    projectId: 'health-care-app-791f6',
    storageBucket: 'health-care-app-791f6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBm2kRSx_CsFA1BhvcU8Is6sU5YxUcLwbI',
    appId: '1:392841827787:ios:your_ios_app_id_here',
    messagingSenderId: '392841827787',
    projectId: 'health-care-app-791f6',
    storageBucket: 'health-care-app-791f6.firebasestorage.app',
    iosClientId: '392841827787-your_ios_client_id.apps.googleusercontent.com',
    iosBundleId: 'com.example.health_care',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBm2kRSx_CsFA1BhvcU8Is6sU5YxUcLwbI',
    appId: '1:392841827787:ios:your_ios_app_id_here',
    messagingSenderId: '392841827787',
    projectId: 'health-care-app-791f6',
    storageBucket: 'health-care-app-791f6.firebasestorage.app',
    iosClientId: '392841827787-your_ios_client_id.apps.googleusercontent.com',
    iosBundleId: 'com.example.health_care',
  );
}
